target 'AppboyProject' do
  platform :ios, '8.0'

  # if you want to integrate through Cocoapods instead of manual linking use this:
  # it already comes with a dependency on `Appboy-iOS-SDK` so you're all set
  # pod 'react-native-appboy-sdk', :path => '../node_modules/react-native-appboy-sdk'

  # Otherwise you still need to depend on the iOS SDK here
  pod 'Appboy-iOS-SDK'

end
