
target 'AppboyProject' do
  platform :ios, '8.0'
  pod 'Appboy-iOS-SDK'

  # if you want to integrate through Cocoapods instead of manual linking
  # pod 'react-native-appboy-sdk', :path => '../node_modules/react-native-appboy-sdk'
end
