target 'HelloReact' do
  platform :ios, '8.0'
  pod 'react-native-appboy-sdk', :path => '../node_modules/react-native-appboy-sdk'
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'DevSupport',
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket'
  ]
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
end
