target 'HelloReact' do
  platform :ios, '9.0'
  pod 'react-native-appboy-sdk', :path => '../node_modules/react-native-appboy-sdk'
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'DevSupport',
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket'
  ]
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
end
